/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package twentyone.frames;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import twentyone.exceptions.ExceptionMenu;
import twentyone.control.GameMenuControl;
import twentyone.maingame.Player;
import twentyone.maingame.Game;
/**
 *
 * @author aziekayrussell
 */
public class GetNamesFrame extends javax.swing.JFrame {

    private Game game = null;
    /**
     * Creates new form GetNamesFrame
     */
   
    public GetNamesFrame(Game game) {
    initComponents();
    this.game = game;
    setLocationRelativeTo(null);
    }
    
    public void initializeForm(){
        if this.game.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMain = new javax.swing.JPanel();
        jlTitle = new javax.swing.JLabel();
        jpForm = new javax.swing.JPanel();
        jlPlayerOne = new javax.swing.JLabel();
        jlPlayer2 = new javax.swing.JLabel();
        jtfPlayer1 = new javax.swing.JTextField();
        jtfPlayer2 = new javax.swing.JTextField();
        jbSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlTitle.setText("jLabel1");

        jlPlayerOne.setText("Player 1 Name:");

        jlPlayer2.setText("Player 2 Name:");

        jbSave.setText("Continue");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpFormLayout = new org.jdesktop.layout.GroupLayout(jpForm);
        jpForm.setLayout(jpFormLayout);
        jpFormLayout.setHorizontalGroup(
            jpFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpFormLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jpFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jtfPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtfPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(14, 14, 14))
            .add(jpFormLayout.createSequentialGroup()
                .add(jpFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpFormLayout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jpFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jlPlayer2)
                            .add(jlPlayerOne)))
                    .add(jpFormLayout.createSequentialGroup()
                        .add(55, 55, 55)
                        .add(jbSave)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jpFormLayout.setVerticalGroup(
            jpFormLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpFormLayout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jlPlayerOne)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtfPlayer1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28)
                .add(jlPlayer2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtfPlayer2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 43, Short.MAX_VALUE)
                .add(jbSave)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jpMainLayout = new org.jdesktop.layout.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpMainLayout.createSequentialGroup()
                .addContainerGap()
                .add(jlTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpMainLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .add(jpForm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(77, 77, 77))
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpMainLayout.createSequentialGroup()
                .addContainerGap()
                .add(jlTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jpForm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpMain, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpMain, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        
    }//GEN-LAST:event_jbSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetNamesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetNamesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetNamesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetNamesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GetNamesFrame().setVisible(true);
                } catch (ExceptionMenu ex) {
                    Logger.getLogger(GetNamesFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSave;
    private javax.swing.JLabel jlPlayer2;
    private javax.swing.JLabel jlPlayerOne;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JPanel jpForm;
    private javax.swing.JPanel jpMain;
    private javax.swing.JTextField jtfPlayer1;
    private javax.swing.JTextField jtfPlayer2;
    // End of variables declaration//GEN-END:variables
}
